require: rubocop-rspec

AllCops:
  TargetRubyVersion: "2.4"
  Exclude:
    - '**/bin/spring'
    - '**/bin/setup'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
    - 'config/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'vendor/**/**'
    - 'app/models/solr_document.rb'


Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/catalog_controller.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/trln_argon_helper.rb'
