development:
  adapter: postgresql
  url: postgresql://%2Ftmp/argon_dev

test:
  adapter: postgresql
  url: postgresql://%2Ftmp/argon_test

production:
  adapter: postgresql
  url: postgresql://%2Ftmp/argon_prod
