SOLR_URL: https://query.discovery.trln.org/trlnbib
LOCAL_INSTITUTION_CODE: duke
PREFERRED_RECORDS: duke
LOCAL_RECORDS: 'duke, trln'
APPLY_LOCAL_FILTER_BY_DEFAULT: "true"
APPLICATION_NAME: TRLN Argon
REFWORKS_URL: 'http://www.refworks.com.libproxy.lib.unc.edu/express/ExpressImport.asp?vendor=SearchUNC&filter=RIS%20Format&encoding=65001&url='
ROOT_URL: 'https://discovery.trln.org'
ARTICLE_SEARCH_URL: 'http://libproxy.lib.unc.edu/login?url=http://unc.summon.serialssolutions.com/search?s.secure=f&s.ho=t&s.role=authenticated&s.ps=20&s.q='
CONTACT_URL: 'https://library.duke.edu/research/ask'
