development:
  preferred_records: <%= ENV['PREFERRED_RECORDS'] || 'unc' %>
  local_institution_code: <%= ENV['LOCAL_INSTITUTION_CODE'] || 'unc' %>
  local_records: <%= ENV['LOCAL_RECORDS'] || 'unc,trln' %>
  apply_local_filter_by_default: <%= ENV['APPLY_LOCAL_FILTER_BY_DEFAULT'] || 'true' %>
  application_name: <%= ENV['APPLICATION_NAME'] || 'TRLN Argon' %>
  refworks_url: <%= ENV['REFWORKS_URL'] || 'http://www.refworks.com.libproxy.lib.unc.edu/express/ExpressImport.asp?vendor=SearchUNC&filter=RIS%20Format&encoding=65001&url=' %>
  root_url: <%= ENV['ROOT_URL'] || 'https://discovery.trln.org' %>
  article_search_url: <%= ENV['ARTICLE_SEARCH_URL'] || 'http://libproxy.lib.unc.edu/login?url=http://unc.summon.serialssolutions.com/search?s.secure=f&s.ho=t&s.role=authenticated&s.ps=20&s.q=' %>
  contact_url: <%= ENV['CONTACT_URL'] || 'https://library.unc.edu/ask/' %>

test:
  preferred_records: <%= ENV['PREFERRED_RECORDS'] || 'unc' %>
  local_institution_code: <%= ENV['LOCAL_INSTITUTION_CODE'] || 'unc' %>
  local_records: <%= ENV['LOCAL_RECORDS'] || 'unc,trln' %>
  apply_local_filter_by_default: <%= ENV['APPLY_LOCAL_FILTER_BY_DEFAULT'] || 'true' %>
  application_name: <%= ENV['APPLICATION_NAME'] || 'TRLN Argon' %>
  refworks_url: <%= ENV['REFWORKS_URL'] || 'http://www.refworks.com.libproxy.lib.unc.edu/express/ExpressImport.asp?vendor=SearchUNC&filter=RIS%20Format&encoding=65001&url=' %>
  root_url: <%= ENV['ROOT_URL'] || 'https://discovery.trln.org' %>
  article_search_url: <%= ENV['ARTICLE_SEARCH_URL'] || 'http://libproxy.lib.unc.edu/login?url=http://unc.summon.serialssolutions.com/search?s.secure=f&s.ho=t&s.role=authenticated&s.ps=20&s.q=' %>
  contact_url: <%= ENV['CONTACT_URL'] || 'https://library.unc.edu/ask/' %>

production:
  preferred_records: <%= ENV['PREFERRED_RECORDS'] || 'unc' %>
  local_institution_code: <%= ENV['LOCAL_INSTITUTION_CODE'] || 'unc' %>
  local_records: <%= ENV['LOCAL_RECORDS'] || 'unc,trln' %>
  apply_local_filter_by_default: <%= ENV['APPLY_LOCAL_FILTER_BY_DEFAULT'] || 'true' %>
  application_name: <%= ENV['APPLICATION_NAME'] || 'TRLN Argon' %>
  refworks_url: <%= ENV['REFWORKS_URL'] || 'http://www.refworks.com.libproxy.lib.unc.edu/express/ExpressImport.asp?vendor=SearchUNC&filter=RIS%20Format&encoding=65001&url=' %>
  root_url: <%= ENV['ROOT_URL'] || 'https://discovery.trln.org' %>
  article_search_url: <%= ENV['ARTICLE_SEARCH_URL'] || 'http://libproxy.lib.unc.edu/login?url=http://unc.summon.serialssolutions.com/search?s.secure=f&s.ho=t&s.role=authenticated&s.ps=20&s.q=' %>
  contact_url: <%= ENV['CONTACT_URL'] || 'https://library.unc.edu/ask/' %>
